In [1]:
# Created by: ADMINIXTRATOR             Date: 9th January, 2020
# Twitter: Adminixtrator                Email: minixtrator@gmail.com
# 
# Pyton verson: 3.7.4 amd64 (64-bit)    TensorFlow: 2.0.0

import tensorflow as tf

tf2x = tf.compat.v1
tf2x.InteractiveSession()

In [2]:
# Before proceeding, please note that a session can be created independently
# The 'tf.Session()' attribute is used in 1x so we will be using 'tf2x' - as defined as 'tf.compat.v1'
# By calling 'sess.run()', the operation within the condition is executed and the result is a 'numpy.ndarray' type


#      TensorFlow 1x 
 
'''    
    sess = tf.Session()
    print(sess.run(tf.constant(2) + tf.constant(4)))
    sess.close()
    
'''

#    WHICH WILL NOT WORK IN 2x

#     TensorFlow 2x

with tf2x.Session() as sess:
    print(sess.run(tf.constant(2) + tf.constant(4)))
    
# You cannot use the 'sess.run()' function and eval attribute together since they are of the same type
# Recall that we made mention of 'tf.eval()' function being equal to 'np.ndarray()'
# The session is closed to release resources

6


In [3]:
# Here is an example of the eval function used outside the IntereactiveSession

with tf2x.Session() as sess:
    print(tf2x.truncated_normal((20,20), mean=0, stddev=1).eval())
    sess.close()

[[ 0.691834   -0.630688    0.00737901 -1.6845964  -0.5796103  -0.04547506
   0.09652811 -0.40031895 -0.01294658  1.660713    0.94868934  1.5483656
  -0.926146    0.5385128  -0.9217892   0.8686556  -0.06881471 -0.73241633
   0.9593492  -0.56229126]
 [ 0.33628365  1.3034931   0.36637694 -1.1503674  -1.2110288  -0.72602934
   0.28544113 -0.09794171  1.1126565   1.5208669  -1.1506116  -0.3276624
  -0.9258054   0.50819886  0.09222075 -0.64237654  0.12364297 -0.3167472
   0.05431825 -0.04666695]
 [-0.39129284 -0.20446533 -0.04757285 -0.62348604  0.06129771 -0.1259803
  -1.524439   -0.7639453   0.14984724  0.47065526 -1.4722745  -1.204934
   0.13486291  1.8245664  -0.45310736 -1.7509024  -0.6115179   0.6310626
   0.9052881  -0.4720887 ]
 [-0.8917792   0.4829569   1.3086864   0.0466794  -0.15981463 -0.4121932
  -1.0493098  -1.6552056  -1.8952951  -0.14077714 -0.51057893 -1.9305142
   0.1879356   1.1149416  -0.3030559  -0.53285307 -0.9209155   0.41522494
   0.4421398   0.49871078]
 [ 1.0853344 

In [4]:
# It can be done as easily as shown below in the interactive session

(tf.constant(2) + tf.constant(4)).numpy()

6

In [5]:
# Tensors can also be Subtracted

a = tf.ones((3,3)) - tf.zeros((3,3))
a.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [6]:
# Alternatively...

with tf2x.Session() as sess:
    a = tf.ones((3,3)) - tf.zeros((3,3))
    sess.close()
a.eval()

# The eval function converts the tensors to a 'numpy.ndarray' type

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
# Tensors can also be multiplied. 
# Note that the multiplication is done differently when dealing with matrices

with tf2x.Session() as sess:
    a = tf.ones((3,3)) * tf.zeros((3,3)) 
    sess.close()
    
a.eval()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
#                        NEXT == Matrix Operations