In [1]:
# Created by: ADMINIXTRATOR             Date: 9th January, 2020
# Twitter: Adminixtrator                Email: minixtrator@gmail.com
# 
# Pyton verson: 3.7.4 amd64 (64-bit)    TensorFlow: 2.0.0

import tensorflow as tf

tf2x = tf.compat.v1
tf2x.InteractiveSession()

In [9]:
# Before proceeding, please note that a session can be created independently
# The 'tf.Session()' attribute is used in 1x so we will be using 'tf2x' - as defined as 'tf.compat.v1'
# By calling 'sess.run()', the operation within the condition is executed and the result is a 'numpy.ndarray' type


#      TensorFlow 1x 
 
'''    
    sess = tf.Session()
    print(sess.run(tf.constant(2) + tf.constant(4)))
    
'''

#    WHICH WILL NOT WORK IN 2x

#     TensorFlow 2x

with tf2x.Session() as sess:
    print(sess.run(tf.constant(2) + tf.constant(4)))
    
# You cannot use the 'sess.run()' function and eval attribute together since they are of the same type
# Recall that we made mention of 'tf.eval()' function being equal to 'np.ndarray()'

6


In [26]:
# Here is an example of the eval function used outside the IntereactiveSession

with tf2x.Session() as sess:
    print(tf2x.truncated_normal((20,20), mean=0, stddev=1).eval())

[[-8.90762150e-01  3.29983711e-01  3.25368494e-01  2.73488224e-01
  -5.71029127e-01  1.81621563e+00 -2.36567989e-01 -7.39876151e-01
  -9.71542478e-01 -4.26373243e-01  4.93569285e-01 -3.96100521e-01
   6.37717605e-01 -9.03377771e-01 -1.85613241e-02  8.76151800e-01
  -3.71321410e-01 -1.96425140e-01  9.25302565e-01  4.74230200e-01]
 [-9.03354406e-01  2.37332404e-01 -1.38816512e+00  4.71695244e-01
  -1.13803923e+00 -1.05546594e+00 -5.60876250e-01 -1.81776285e+00
  -1.23929024e-01 -4.55926090e-01  9.91463542e-01 -1.01959908e+00
  -1.21000671e+00 -1.22327521e-01  1.89139441e-01  3.49673957e-01
  -1.57446742e-01 -2.89898843e-01  5.98858178e-01 -1.14794743e+00]
 [-2.14003369e-01 -1.24912250e+00 -4.47420210e-01  3.07746500e-01
  -1.13260281e+00  1.39579609e-01  1.36609096e-02 -9.58687603e-01
  -1.19392157e+00 -1.09862113e+00 -8.75403509e-02  1.16828370e+00
  -7.65174389e-01 -1.29143322e+00 -1.55045187e+00 -6.65908903e-02
  -2.27781177e-01  1.26897800e+00  2.19528228e-01  1.72502649e+00]
 [-7.44

In [14]:
# It can be done as easily as shown below in the interactive session

(tf.constant(2) + tf.constant(4)).numpy()

6

In [27]:
# Tensors can also be Subtracted

a = tf.ones((3,3)) - tf.zeros((3,3))
a.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [62]:
# Alternatively...

with tf2x.Session() as sess:
    
    
    a = tf.ones((3,3)) - tf.zeros((3,3))
    print(sess.run(a))
    
a.eval()

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [8]:
# Using the eval function...

with tf2x.Session() as sess:
    a = tf.ones((3,3)) - tf.zeros((3,3)) 
    a = sess.run(a)
    a
    
# The eval function can be called outside the condition statement as shown below to get the 'numpy.ndarray' type,
# likewise the sess.run() function 

a.eval()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [64]:
# A session can be closed by calling the 'sess.close()' function 

with tf2x.Session() as sess:
    a = tf.ones([3,3]) - tf.zeros([3,3])  
    print(sess.run(a).eval())
    sess.close()
    

AttributeError: 'numpy.ndarray' object has no attribute 'eval'

In [63]:
with tf2x.Session() as sess:
    a = tf.constant(3) - tf.constant(4)
    print(a.eval())

-1
