In [1]:
# Created by: ADMINIXTRATOR             Date: 9th January, 2020
# Twitter: Adminixtrator                Email: minixtrator@gmail.com
# 
# Pyton verson: 3.7.4 amd64 (64-bit)    TensorFlow: 2.0.0

import tensorflow as tf

# Tesnsorflow can now be used as'tf.<Operation>'
# For Verson 1x.. all attributes remain the same

In [2]:
# To use TensorFlow 2x, you need to add '.compat.v1' before the attribute
# Although you can define your TF 2x to behave like 1x

tf.compat.v1.InteractiveSession()

# Experimenting with tensorflow interactively

In [3]:
# Another way to make our lives easier is to declare another variable to hold the module 'tf.compat.v1'

tf2x = tf.compat.v1

In [5]:
tf2x.InteractiveSession()

# Voila.. 
# Now all other attributes will be addressed with 'tf2x.<Session>'

In [6]:
# The easiest conventions in creating a Tensor are 'tf.zeros' and 'tf.ones'
# To show the created Tensor you call 'tf.Tensor.eval()' - in this case, it will be 'tf.Tensor.numpy()' since we are in an 
# interactive session
# The 'tf.eval' is the same as your 'np.ndarray' - Numpy
# TensorFlow was built to be compatible with Numpy conventions

tf.zeros(2)

<tf.Tensor: id=3, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [7]:
#   tf.zeros((3,3)).eval()    Used in 1x, doesn't work in 2x

tf.zeros((3,3)).numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [8]:
tf.ones((2,2,2)).numpy()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [9]:
# Another method is the 'tf.fill()' - create tensors of quantities beside 1/0
# The 'tf.constant()' is used to create Tensors that will not change throughout the program execution

tf.fill((3,3), value=3).numpy()

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [10]:
tf.constant(12).numpy()

12

In [11]:
# Tensors can also be created using the 'tf.random_normal' - this is an attribute
# Here you can specify the mean and standard deviation of then random values

tf2x.random_normal((3,3), mean=1, stddev=2).numpy()

array([[ 3.0637124 ,  3.1123064 ,  6.071253  ],
       [ 1.986774  , -2.1183703 , -0.96934974],
       [-1.0016227 ,  1.6871884 ,  1.1689787 ]], dtype=float32)

In [12]:
# Another attribute is the 'tf.truncated_normal()' - this is used when working with large samples
# Due to Numerical Stability, it is advisable to use this attribute

tf2x.truncated_normal((50,50), mean=0.1, stddev=3).numpy()

array([[ 2.4664335 ,  0.290219  ,  1.8901488 , ..., -2.536847  ,
        -0.850695  , -4.378546  ],
       [ 0.4260654 ,  1.2101666 , -3.9902601 , ..., -0.30073103,
        -2.1110048 ,  4.7401285 ],
       [ 1.5350013 , -5.265534  , -0.2630674 , ..., -1.1164607 ,
        -0.3360285 , -1.3886522 ],
       ...,
       [ 4.5753374 , -3.7473583 , -5.0688014 , ..., -0.49745372,
         1.4778258 ,  1.8254855 ],
       [ 2.4004138 ,  1.2835901 ,  3.060084  , ...,  1.6021315 ,
        -2.5343332 ,  4.3240113 ],
       [ 2.097033  , -2.5208745 ,  1.7857302 , ..., -1.476527  ,
         1.3403462 ,  2.9828706 ]], dtype=float32)

In [13]:
# The 'tf.random_uniform' also behaves like the random_normal, except that it is specified a range
# It's values are sampled from a Uniform Distribution - hence the name

tf2x.random_uniform((3,3), minval=0, maxval=1).numpy()

array([[0.6906148 , 0.13998473, 0.7907686 ],
       [0.50875056, 0.4754063 , 0.30271518],
       [0.4017985 , 0.30022037, 0.07988465]], dtype=float32)

In [ ]:
#                        NEXT == Tensor Addition and Scaling